services:
    [[db_service]]:
        image: mysql:8
        restart: always
        container_name: [[db_service]]
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_app
            MYSQL_USER: my_app
            MYSQL_PASSWORD: secret
        volumes:
            - ./:/application
        ports:
            - '[[db_port]]:3306'

    [[web_service]]:
        build:
            dockerfile: php/Dockerfile
        container_name: [[web_service]]
        working_dir: /application/webroot
        volumes:
            - ./:/application
        environment:
            - WEB_DOCUMENT_ROOT=/application/webroot
            - DATABASE_URL=mysql://my_app:secret@[[db_service]]/my_app
            - DATABASE_TEST_URL=mysql://root:root@[[db_service]]/my_app
            - SHORT_NAME=[[short_name]]
            - WEB_PORT=[[web_port]]
            - DB_PORT=[[db_port]]
        ports:
            - "[[web_port]]:80"

#volumes:
#    mysqldata:
