services:
    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
            MYSQL_DATABASE: ${SHORT_NAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_USER_PASS}
#        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - ./:/application
        ports:
            - "${DB_PORT}:3306"

    cakephp:
        build:
            dockerfile: docker/cakephp/Dockerfile
        working_dir: /application/webroot
        volumes:
            - ./:/application
        environment:
            - WEB_DOCUMENT_ROOT=/application/webroot
            - DATABASE_URL=mysql://my_app:secret@${DB_SERVICE}/${SHORT_NAME}
            - DATABASE_TEST_URL=mysql://root:root@${DB_SERVICE}/test_${SHORT_NAME}
            - SHORT_NAME=${SHORT_NAME}
            - WEB_PORT=${WEB_PORT}
            - DB_PORT=${DB_PORT}
        ports:
            - "${WEB_PORT}:80"

#volumes:
#    mysqldata:
